// Auto-generated by scripts/bump-version.mjs during build. Do not edit manually.
export const APP_VERSION = '2.0.64';
export const BUILD_TIMESTAMP = '2026-09-07T11:50:37.310Z';
export const APP_NAME = 'ChoPaeng';
