// Auto-generated by scripts/bump-version.mjs during build. Do not edit manually.
export const APP_VERSION = '2.0.44';
export const BUILD_TIMESTAMP = '2026-09-07T03:43:40.213Z';
export const APP_NAME = 'ChoPaeng';
