// Auto-generated by scripts/bump-version.mjs during build. Do not edit manually.
export const APP_VERSION = '2.0.41';
export const BUILD_TIMESTAMP = '2026-09-06T02:11:09.153Z';
export const APP_NAME = 'ChoPaeng';
